### PR TITLE
Remove rust-toolchain and fix some typos

### PR DESCRIPTION
**Pull request by zhzy0077**
Due to the name changes, https://github.com/rust-lang/rust/pull/51919, to_bytes has renamed to to_ne_bytes. After the change, we don't need to specify the toolchain version.
Also some typos and needless lifetimes have been fixed.

### CODE REVIEW

**Comment by cswinter** [comment]
Nice, thanks for the contribution!

I think there is still value in keeping the rust-toolchain to guard against any future changes to nightly Rust and make it unnecessary to manually update the compiler version.

**Comment by zhzy0077** [comment]
@cswinter Well, it would be better if we can update toolchain version since we are unable to use clippy on current version.
```
toolchain 'nightly-2018-07-18-x86_64-apple-darwin' does not have the binary `cargo-clippy`
```

**Comment by cswinter** [comment]
@zhzy0077 Oh for sure, please do update the toolchain to the latest version! Having clippy would be great, and not letting the version fall too far behind is good also.

**Comment by cswinter** [comment]
Thanks again!

**Pull request merged**
